title: SourceShield | Docs
description: SourceShield Documentation
theme: just-the-docs

url: https://docs.sourceshield.io

aux_links:
  SourceShield: https://sourceshield.io
  Blog: https://blog.sourceshield.io

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: light

footer_content: "Copyright 2023 • SourceShield"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: https://github.com/SourceShield/docs
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow

twitter:
  username: SourceShield